### ISSUE TITLE
java.lang.NullPointerException in MainActivity

### ISSUE THREAD

**Issue by basti12354** [Deveshbhatla/AR#1]
I clicked on AR button to open MainActivity. After that I moved my phone until some planes are detected. Now I tapped somewhere on the display and the application crashed. Here are the logs.

2020-11-26 23:50:26.948 3182-3182/? E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
        at com.example.ar.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:30)
        at com.example.ar.-$$Lambda$MainActivity$xvkDik1KQzlZpZxDm9mU414E15Y.onTapPlane(Unknown Source:2)
        at com.google.ar.sceneform.ux.BaseArFragment.onSingleTap(BaseArFragment.java:576)
        at com.google.ar.sceneform.ux.BaseArFragment.access$000(BaseArFragment.java:68)
        at com.google.ar.sceneform.ux.BaseArFragment$1.onSingleTapUp(BaseArFragment.java:185)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:756)
        at com.google.ar.sceneform.ux.BaseArFragment.onPeekTouch(BaseArFragment.java:509)
        at com.google.ar.sceneform.TouchEventSystem.onTouchEvent(SourceFile:21)
        at com.google.ar.sceneform.Scene.onTouchEvent(SourceFile:127)
        at com.google.ar.sceneform.SceneView.onTouchEvent(SourceFile:24)
        at android.view.View.dispatchTouchEvent(View.java:13524)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3217)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2910)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3217)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2910)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3217)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2910)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3217)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2910)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3217)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2910)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3217)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2910)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3217)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2910)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:652)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1988)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4146)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:598)
        at android.view.View.dispatchPointerEvent(View.java:13787)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5888)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5683)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5127)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5180)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5146)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5303)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5154)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5360)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5127)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5180)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5146)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5154)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5127)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8035)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7986)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7940)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8228)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:233)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:363)
    	at android.os.Looper.loop(Loop

**Comment by Deveshbhatla** [comment]
I'll look into it. Although, this application's main use is to select the image from gallery and then display it in AR form(it is dynamic and the image is selected from yours phone storage). The AR button displays the image that is in the drawable directory, i.e. it is static and stored internally in the app.
